# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-01-14 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registeration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.PositiveIntegerField(max_length=10, unique=True),
        ),
    ]
