# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-01-14 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registeration', '0002_auto_20190114_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
