# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-05 21:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Carts', '0003_auto_20181106_0223'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(blank=True, max_length=150)),
                ('status', models.CharField(choices=[('created', 'Created'), ('paid', 'Paid'), ('in progress', 'In Progress'), ('delivered', 'Delivered'), ('refunded', 'Refunded')], default='created', max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('paid', models.BooleanField(default=False)),
                ('delivery_charges', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('order_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('active', models.BooleanField(default=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Carts.Cart')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
