# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-05 21:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_charges',
            field=models.DecimalField(decimal_places=2, default=20.0, max_digits=5),
        ),
    ]
