# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-16 15:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Addresses', '0001_initial'),
        ('Orders', '0004_order_billing_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Addresses.Address'),
        ),
    ]
